# Warning: This file created from template automatically. Please, don't change it manually.
# If you need to change the template, please, change the original template file.
# https://github.com/pdffiller/health_monitoring/blob/main/templates/health-check.yml
# All your changes will be lost after the generation process.
name: Run Health Check

on:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  health-check:
    uses: pdffiller/health_monitoring/.github/workflows/health-check.yml@main
    secrets: inherit
